name: Matt Jibson
email: matt.jibson@gmail.com
markdown: redcarpet
pygments: true
url: htp://mattjibson.com
permalink: /blog/:year/:month/:day/:title

# Disqus Comments
disqus_short_name: mjibson-blog

# Google Analytics
google_analytics_tracking_id: UA-26568697-1