markdown:         redcarpet
pygments:         true
permalink:        /blog/:year/:month/:day/:title/
title:            Matt Jibson
author:
  name: Matt Jibson
  email: matt.jibson@gmail.com
tagline:          'blog'
description:      'Dev at Stack Overflow. Pianist & organist.'
url:              http://mattjibson.com
paginate:         5

google_analytics_tracking_id: UA-26568697-1
