markdown:         redcarpet
pygments:         true
permalink:        /blog/:year/:month/:day/:title/
title:            Matt Jibson
author:
  name: Matt Jibson
  email: matt.jibson@gmail.com
tagline:          'blog'
description:      'Dev at Cockroach Labs. Pianist & organist.'
url:              https://mattjibson.com

google_analytics_tracking_id: UA-26568697-1
